pipeline {
  agent any

  environment {
    DOCKERHUB_USER = 'pankaj6190'
    IMAGE_NAME     = 'web-server'
    IMAGE_TAG      = "${env.BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
          docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG .
          docker tag  $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG \
                      $DOCKERHUB_USER/$IMAGE_NAME:latest
        '''
      }
    }

    stage('Push to DockerHub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
            docker push $DOCKERHUB_USER/$IMAGE_NAME:latest
          '''
        }
      }
    }

    stage('Update K8s Manifest') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'github-creds',
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_PASS'
        )]) {
          sh '''
            git config user.email "jenkins@ci.local"
            git config user.name "Jenkins"
            sed -i "s|image: $DOCKERHUB_USER/$IMAGE_NAME:.*|image: $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG|g" k8s/deployment.yaml
            git add k8s/deployment.yaml
            git commit -m "ci: update image to build-$IMAGE_TAG [skip ci]"
            git push https://$GIT_USER:$GIT_PASS@github.com/YOUR_USERNAME/k8s-demo-app.git HEAD:main
          '''
        }
      }
    }

  }

  post {
    success { echo '✅ Deployed! ArgoCD will sync in seconds.' }
    failure { echo '❌ Build failed. Check logs above.' }
  }
}
